name: anicat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  beautiful_soup_dart: ^0.3.0

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_video_view: ^2.1.1
  video_thumbnail:
    git:
      url: https://github.com/Shahidbangash/video_thumbnail.git
      ref: master
  crypto: ^3.0.6
  image: ^4.5.2
  permission_handler: ^11.3.1
  filesystem_picker: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true