// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<HeaderMap?> getHeader() =>
    RustLib.instance.api.crateApiConfigHeaderGetHeader();

Future<HeaderMap?> getHeaderCookies() =>
    RustLib.instance.api.crateApiConfigHeaderGetHeaderCookies();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HeaderMap>>
abstract class HeaderMap implements RustOpaqueInterface {}
