org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
kotlin.incremental.js=false
kotlin.incremental.jvm=false
kotlin.daemon.useFallbackStrategy=false
kotlin.incremental.useClasspathSnapshot=false
kotlin.build.report.output=file